import type { Property } from "./types";

export const demoProperties: Property[] = [
  {
    id: 1,
    hostId: 2,
    hostName: "Aarav Sharma",
    title: "Sunset Courtyard Villa",
    slug: "sunset-courtyard-villa-goa",
    description:
      "A bright Portuguese-inspired villa with a private courtyard near the coast.",
    addressLine: "12 Fontainhas Lane",
    city: "Goa",
    country: "India",
    capacity: 6,
    bedrooms: 3,
    bathrooms: 2.5,
    basePrice: 6200,
    averageRating: 4.9,
    reviewCount: 28,
    active: true,
    coverImage: "/images/goa-villa.svg",
    amenities: ["Wi-Fi", "Pool", "Kitchen", "Beach access"],
  },
  {
    id: 2,
    hostId: 2,
    hostName: "Aarav Sharma",
    title: "Pine Ridge Cabin",
    slug: "pine-ridge-cabin-manali",
    description:
      "A quiet timber cabin with mountain views, a fireplace, and a dedicated workspace.",
    addressLine: "44 Old Manali Road",
    city: "Manali",
    country: "India",
    capacity: 4,
    bedrooms: 2,
    bathrooms: 2,
    basePrice: 4800,
    averageRating: 4.8,
    reviewCount: 19,
    active: true,
    coverImage: "/images/manali-cabin.svg",
    amenities: ["Wi-Fi", "Mountain view", "Parking", "Workspace"],
  },
  {
    id: 3,
    hostId: 2,
    hostName: "Aarav Sharma",
    title: "Pink City Heritage Loft",
    slug: "pink-city-heritage-loft-jaipur",
    description:
      "A restored city loft within walking distance of Jaipur landmarks and local markets.",
    addressLine: "8 Badi Chaupar",
    city: "Jaipur",
    country: "India",
    capacity: 3,
    bedrooms: 1,
    bathrooms: 1,
    basePrice: 3400,
    averageRating: 4.7,
    reviewCount: 34,
    active: true,
    coverImage: "/images/jaipur-loft.svg",
    amenities: ["Wi-Fi", "Air conditioning", "Kitchen"],
  },
  {
    id: 4,
    hostId: 2,
    hostName: "Aarav Sharma",
    title: "Lakeside Studio Retreat",
    slug: "lakeside-studio-retreat-udaipur",
    description:
      "A calm studio overlooking the lake, designed for couples and solo travellers.",
    addressLine: "19 Ambrai Ghat",
    city: "Udaipur",
    country: "India",
    capacity: 2,
    bedrooms: 1,
    bathrooms: 1,
    basePrice: 3900,
    averageRating: 4.9,
    reviewCount: 16,
    active: true,
    coverImage: "/images/udaipur-studio.svg",
    amenities: ["Wi-Fi", "Lake view", "Kitchen", "Workspace"],
  },
];
